[build]
  functions = "LeaderboardBackend/netlify/functions"

[functions]
  directory = "LeaderboardBackend/netlify/functions"

[functions."cleanupLeaderboard"]
  schedule = "0 0 1 * *"  # 毎月1日 0時に実行
